gitSourceBranch = "main"

[[classOrder]]
section = "CargoSemver"
classes = ["Version", "Prerelease", "BuildMetadata", "VersionReq", "Comparator"]

[docusaurus]
tagline = "A parser and evaluator for Cargo's flavor of Semantic Versioning"

[home]
enabled = true
includeReadme = false

[[home.features]]
title = "Simple"
description = "Provides a simple and idiomatic Luau API wrapper for the low-level Rust-style API."

[[home.features]]
title = "Robust"
description = "Passes every test included in the original Rust crate."

[[home.features]]
title = "Performant"
description = "Achieves great performance by parsing and evaluating semantic versions without creating unnecessary substrings."
