[tools]
rojo = "rojo-rbx/rojo@7.5.1"
wally = "UpliftGames/wally@0.3.2"
selene = "Kampfkarren/selene@0.29.0"
stylua = "johnnymorganz/stylua@2.1.0"
luau-lsp = "johnnymorganz/luau-lsp@1.53.1"
lune = "lune-org/lune@0.10.1"
