[tools]
rojo = "rojo-rbx/rojo@7.6.1"
wally = "UpliftGames/wally@0.3.2"
selene = "Kampfkarren/selene@0.31.0"
stylua = "johnnymorganz/stylua@2.5.2"
luau-lsp = "johnnymorganz/luau-lsp@1.68.0"
lute = "luau-lang/lute@1.0.0"
