name: Build

on:
  push:
    branches:
      - main
    paths:
      - "lib/**"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install tools using Rokit
        uses: CompeyDev/setup-rokit@v0.2.1
        with:
          cache: true

      - name: Build Roblox model
        run: rojo build default.project.json -o luau-cargo-semver.rbxm

      - name: Upload Roblox model as artifact
        uses: actions/upload-artifact@v7
        with:
          path: luau-cargo-semver.rbxm
          archive: false
          if-no-files-found: error
