name: Build

on:
  push:
    branches:
      - main
    paths:
      - "lib/**"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tools using Rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Build Roblox source
        run: lune run build-roblox-source.luau

      - name: Build Roblox model
        run: rojo build roblox-model.project.json -o luau-cargo-semver.rbxm

      - name: Upload Roblox model as artifact
        uses: actions/upload-artifact@v4
        with:
          name: roblox-model
          path: luau-cargo-semver.rbxm
          if-no-files-found: error
