name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tools using Rokit
        uses: CompeyDev/setup-rokit@v0.1.2
        with:
          cache: true

      - name: Analyze
        run: luau-lsp analyze --definitions=.vscode/definitions/testez.d.luau --base-luaurc=.luaurc lib

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tools using Rokit
        uses: CompeyDev/setup-rokit@v0.1.2
        with:
          cache: true

      - name: Lint
        run: selene ./lib

  style:
    name: Styling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tools using Rokit
        uses: CompeyDev/setup-rokit@v0.1.2
        with:
          cache: true

      - name: Run StyLua check
        run: stylua --check ./lib

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tools using Rokit
        uses: CompeyDev/setup-rokit@v0.1.2
        with:
          cache: true

      - name: Run tests
        run: lune run test
